---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adminbhavin/public_html/
    - /bin/cp -R service $DEPLOYPATH
    - /bin/cp -R model $DEPLOYPATH
    - /bin/cp -R utils $DEPLOYPATH
    - /bin/cp -R validation $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp config/* $DEPLOYPATH/config/
    - /bin/cp .env $DEPLOYPATH
    # Install dependencies
    - cd $DEPLOYPATH
    - /usr/local/bin/npm install --production
    
